# Generated by Django 4.0.4 on 2022-05-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='files/'),
        ),
    ]
