# Generated by Django 4.0.4 on 2022-06-11 20:01

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_post_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=portfolio.models.resolution_path),
        ),
    ]
