# Generated by Django 4.0.5 on 2022-06-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_post_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='portfolio\\static\\portfolio\\images\\img_proj'),
        ),
    ]
